src/main/java/com/demo/entity/Address.java
package com.demo.entity;

/**
 * @author Gerardo Larín
 */
public class Address {
    private String street;
    private String suite;
    private String city;
    private String zipcode;
    private Geo geo;

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getSuite() {
        return suite;
    }

    public void setSuite(String suite) {
        this.suite = suite;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public Geo getGeo() {
        return geo;
    }

    public void setGeo(Geo geo) {
        this.geo = geo;
    }
    
    
}

src/main/java/com/demo/entity/Company.java
package com.demo.entity;

/**
 * @author Gerardo Larín
 */
public class Company {
    private String name;
    private String catchPhrase;
    private String bs;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCatchPhrase() {
        return catchPhrase;
    }

    public void setCatchPhrase(String catchPhrase) {
        this.catchPhrase = catchPhrase;
    }

    public String getBs() {
        return bs;
    }

    public void setBs(String bs) {
        this.bs = bs;
    }
    
    
}

src/main/java/com/demo/entity/Geo.java
package com.demo.entity;

/**
 * @author Gerardo Larín
 */
public class Geo {
    private String lat;
    private String lng;

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }
    
    
}

src/main/java/com/demo/entity/Usuarios.java
package com.demo.entity;

import java.io.Serializable;

/**
 * @author Gerardo Larín
 */
public class Usuarios implements Serializable {
    private int id;
    private String name;
    private String username;
    private String email;
    private Address address;
    private String phone;
    private String website;
    private Company company;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    
}

src/main/java/com/demo/testadaptatechnologies/SessionBean.java
package com.demo.testadaptatechnologies;

import com.demo.entity.Usuarios;
import java.io.Serializable;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

/**
 *
 * @author Gerardo Larín
 */
@ManagedBean(name = "sessionBean")
@RequestScoped
public class SessionBean implements Serializable {

    public SessionBean() {
    }
    
    public void checkSession() {
        try {
            FacesContext context = FacesContext.getCurrentInstance();
            Usuarios us = (Usuarios) context.getExternalContext().getSessionMap().get("Usuario");

            if (us == null) {
                context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Aviso!", "Debes de iniciar sesión para comenzar."));
                context.getExternalContext().redirect(context.getExternalContext().getRequestContextPath() + "/fail.xhtml");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    public Usuarios getUser() {
        return (Usuarios) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("Usuario");
    }
    
}

src/main/webapp/fail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>ERROR</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link type = "text/css" rel = "stylesheet" href = "css/bootstrap.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/bootstrap.min.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/font-awesome.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/font-awesome.min.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/loginStyle.css" />
    </h:head>
    <h:body>
        <div class="container">
            <p:panel>
                <p:outputLabel value="No ha iniciado sesión. &emsp;"/>
                <p:link value="Regresar a página principal" outcome="index.xhtml"/>
            </p:panel>
        </div>
    </h:body>
</html>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>Login</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link type = "text/css" rel = "stylesheet" href = "css/bootstrap.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/bootstrap.min.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/font-awesome.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/font-awesome.min.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/loginStyle.css" />
    </h:head>
    <h:body>
        <div class="container">
            <header>
                <p:outputLabel value="¡Bienvenido!"/>	
            </header>
            <section>
                <div id="container_demo" >
                    <a class="hiddenanchor" id="toregister"></a>
                    <a class="hiddenanchor" id="tologin"></a>
                    <div id="wrapper">
                        <div id="login" class="animate form">
                            <h:form id="loginForm"> 
                                <h1>Iniciar Sesión</h1> 
                                <p:messages id="msgLog" severity="fatal, warn" showDetail="true" autoUpdate="false" closable="true"/>
                                <p:growl id="loginError" severity="error" showSummary="false" showDetail="true" autoUpdate="false" life="5000"/>
                                <p> 
                                    <label for="username" class="uname" > Nombre de usuario: </label>
                                    <h:inputText id="username" value="#{staffWebService.username}" autocomplete="off" required="true" label="ID de Usuario"/>
                                </p>
                                <p id="usrError" style="width: 100%; height: 1px;">
                                    <p:commandLink value="¿Ha olvidado su usuario?" oncomplete="PF('userRecover').show();" class="btn btn-link btn-sm" rendered="#{systemBean.error == 1}" update=":frmUserRecover:" style="margin: -15px; padding: 0px; float: right;"/>
                                </p>
                                <p> 
                                    <label for="password" class="youpasswd"> Contraseña: </label>
                                    <h:inputSecret id="password" value="#{staffWebService.pswUsr}" required="true" label="Contraseña"/>
                                </p>
                                <p id="pssdError" style="width: 100%; height: 5px;">
                                    <p:commandLink value="¿Ha olvidado su contraseña?" class="btn btn-link btn-sm" style="margin: -15px; padding: 0px; float: right;"/>
                                </p>
                                <p class="login button">
                                    <p:commandButton value="Ingresar" action="#{staffWebService.log_in()}" class="btn btn-danger btn-lg"/>
                                </p>
                                <p class="change_link">
                                    ¿Aún no eres miembro?
                                    <a href="#toregister" class="to_register">Únete a nosotros</a>
                                </p>
                            </h:form>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </h:body>
</html>

src/main/webapp/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:a="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <title>Bienvenido</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link type = "text/css" rel = "stylesheet" href = "css/bootstrap.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/bootstrap.min.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/font-awesome.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/font-awesome.min.css" />
        <link type = "text/css" rel = "stylesheet" href = "css/loginStyle.css" />
        <f:event type="preRenderView" listener="#{sessionBean.checkSession()}"/>
    </h:head>
    <h:body>
        <div class="container">
            <h:form id="principal">
                <p:panel>
                    <p:outputLabel value="Hola '#{sessionBean.user.name}' sea usted bienvenido! &emsp;"/>
                    <p:commandButton value="Cerrar Sesión" action="#{staffWebService.cerrarSesion()}"/>
                </p:panel>
            </h:form>
        </div>
    </h:body>
</html>